DROP TABLE IF EXISTS works;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS certify;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS empschedule;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS invschedule;